### ISSUE TITLE
Run-length encoding for buffer in drawing log file.

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/simulator#2]
Using simple Run-length encoding we could greatly reduce the size of the drawing log file.

Example:
Now: B;P1;CCCCCCCCLLLL
After: B;P1;8C4L

**Comment by utkarsh858** [comment]
Can I can implement it?

**Comment by cristobalmedinalopez** [comment]
Hi @utkarsh858, sorry but it is not already necessary because we are going to change the way in which buffer is stored. In any case, thanks for your interest.
