### ISSUE TITLE
Feeding the simulator with a real source

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [P2PSP/simulator#29]
At this moment, we simulate that the chunks of stream are received by the splitter, at a chunk-rate controlled by a `sleep()`. In the current implementation, the chunks are "empty" (only a single character is transmitted). This is quite simple, but the simulation times are not accurate.

The splitter, as in a real situation, should be fed by an Icecast or VLC instances. The chunks should be transmitted.

We can control the number of transmitted chunks per second by changing the chunk size and the stream bit-rate (using, for example, stream with different bit-rates).

**Comment by Pac23** [comment]
I have been looking into this for couple of days now  and icecast does not seem to have clear documentation,implementing chunk sizes as per the bit rate of the file would be possible though but that is not the optimal solution i guess ?

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @Pac23. Icecast is a simple HTTP streaming server and P2PSP does not understand (in the current implementation) what is broadcasting. I tell you this, because we don't need to know the bit-rate of the stream, nor the Theora page size. The splitter should be a simple Web client (such as a firefox instance) that retrieves the stream using HTTP, splits the stream into chunks and send them to the team.

This procedure was used from the beginning in the original Python source files. Head over https://github.com/P2PSP/core/blob/master/src/core/splitter_ims.py and https://github.com/P2PSP/core/blob/master/src/core/splitter_dbs.py.

**Comment by Pac23** [comment]
is a web instance necessary ? this can be achieved without one.

**Comment by vicente-gonzalez-ruiz** [comment]
> Sorry for the delay my finals just got over,anyways

It's OK :-)

> is a web instance necessary?

Do you mean, to use HTTP? This is the most common "transport" protocol for streaming media.

**Comment by Pac23** [comment]
> Do you mean, to use HTTP? This is the most common "transport" protocol for streaming media.

Offcourse HTTP is required , what i meant is is a firefox instance required ?

**Comment by vicente-gonzalez-ruiz** [comment]
Firefox can be used to test if the streaming server is working. It is not required.

**Comment by Pac23** [comment]
so what i have done is i have added a argumentparser that will allow the user to change the chunk size.i have set the standard chunk size at 1024.Since the protocol won't need to know the bit rate otherwise this could have been done dynamically.  

Also just so you know i am doing this as a separate splitter file that has to be integrated in the main simulator to enable the feed this is what i understood from your above explanation,i am wondering if this is the right approach.I am only asking this to avoid unnecessary waste of time working on the wrong appraoch ? total noob sorry for asking so many questions.

**Comment by vicente-gonzalez-ruiz** [comment]
@Pac23, thank you for your time. Have you seen the original implementation of P2PSP in Python? In relation to this:

> I am doing this as a separate splitter file that has to be integrated in the main simulator

Well, it is an option. But I think that the simplest procedure would be to work in the current files (in your branch, of course) and when the things go right, perform a PR. But, this is up to you. Use the strategy more comfortable for you.

**Comment by Pac23** [comment]
Yes i have seen the core directory as per your older comment,also saw the slitter_old.py since the main splitter.py file couldn't be found. 

I am bit confused/have a questions the splitter_ims and the other rule files are not supposed to be touched right ?

**Comment by vicente-gonzalez-ruiz** [comment]
> I am bit confused/have a questions the splitter_ims and the other rule files are not supposed to be touched right ?
Sorry @Pac23, I don't understand your question. Are you asking for whether the rest of P2PSP set of rules (IMS, NTS, ...) should be affected by this improvement (the use of a real video source)? The answer is yes, of course, although not directly in the code. Once we are able to use a video source, the whole simulator should use this functionality.

**Comment by Pac23** [comment]
No,what i meant was the additional code to retrive and stream should be in the main simulator.py right and no directly in the set of rules. Was a dumb question to begin with,idk why i asked this

**Comment by vicente-gonzalez-ruiz** [comment]
OK @Pac23, now I understand the question.

I would include the code in the most basic layer (DBS) of the splitter.

**Comment by Pac23** [comment]
oh,thanks this make things a lot clear 👍

**Comment by Pac23** [comment]
so done with it atleast the main working parts,do you have icecast documentation other than the standard method of running a source mentioned in the how to use repo ? i am getting some connection errors while testing it.Pretty sure it has got something to do with the method used to initialize the stream.

**Comment by vicente-gonzalez-ruiz** [comment]
See https://slides.p2psp.org/2017-12-Elche/index.html

Which are the errors?

**Comment by Pac23** [comment]
connection refused,i have troubleshoted it a lot,hope will find the issue soon.

**Comment by vicente-gonzalez-ruiz** [comment]
Sounds like the server is not running. Can you find its process id?

**Comment by Pac23** [comment]
yup doing 

`sudo netstat -nlp | grep 8000` 

leads to nothing but in the console the it shows that the process is running,even the process id shows that,even streaming using the gui,look at [this](https://imgur.com/a/6kGqVWa) screenshot the error if i am not wrong is caused by the peer_dbs connecting to the wrong ip.

**Comment by vicente-gonzalez-ruiz** [comment]
Run

`telnet localhost 8000`

and tell me.

**Comment by vicente-gonzalez-ruiz** [comment]
OK, @Pac23. Thank you for the info.

Which video (more exactly, I'm asking about the duration) is Icecast serving and how it is served it to Icecast?

**Comment by Pac23** [comment]
big buck bunny video,it is being served using the lab2.sh script from https://slides.p2psp.org/2017-12-Elche/index.html commented out the second vid source.  

In firefox i can see the vid manipulation bar and even manipulate it. I have even checked the icecast.xml config file which is upto standard with proper port and ip settings. 

https://imgur.com/a/yNmtuW1

**Comment by Pac23** [comment]
https://github.com/Pac23/simulator/blob/master/src/core/splitter_dbs.py

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @Pac23, sorry for the delay. When a run your code, I get:

```
[vruiz@pluton src]$ python3 -u simulator.py run
2018-07-01 23:13:01,283 - __main__ - CRITICAL - Critical messages enabled.
2018-07-01 23:13:01,283 - __main__ - ERROR - Error messages enabled.
2018-07-01 23:13:01,283 - __main__ - WARNING - Warning message enabled.
2018-07-01 23:13:01,283 - __main__ - INFO - Informative message enabled.
2018-07-01 23:13:01,283 - __main__ - DEBUG - Low-level debug message enabled.
2018-07-01 23:13:01,283 - __main__ - INFO - set_of_rules        = "dbs"
2018-07-01 23:13:01,283 - __main__ - INFO - number_of_peers     = 9
2018-07-01 23:13:01,283 - __main__ - INFO - number_of_monitors  = 1
2018-07-01 23:13:01,283 - __main__ - INFO - number_of_rounds    = 100
2018-07-01 23:13:01,283 - __main__ - INFO - number_of_malicious = 1
2018-07-01 23:13:01,293 - __main__ - INFO - simulator: platform.system() = Linux
2018-07-01 23:13:01,366 - core.splitter_dbs - CRITICAL - Critical messages enabled.
2018-07-01 23:13:01,366 - core.splitter_dbs - ERROR - Error messages enabled.
2018-07-01 23:13:01,366 - core.splitter_dbs - WARNING - Warning message enabled.
2018-07-01 23:13:01,366 - core.splitter_dbs - INFO - Informative message enabled.
2018-07-01 23:13:01,366 - core.splitter_dbs - DEBUG - Low-level debug message enabled.
Process Process-3:
Traceback (most recent call last):
  File "/home/vruiz/.pyenv/versions/3.6.4/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/vruiz/.pyenv/versions/3.6.4/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "simulator.py", line 94, in run_a_splitter
    splitter = Splitter_DBS()
  File "/tmp/simulator/src/core/splitter_dbs.py", line 88, in __init__
    _p_("Buffer size (in chunks) =", self.BUFFER_SIZE)
NameError: name '_p_' is not defined
```

Which command do you use for running the simulator?

Another question, how do you specify the end-point of the Icecast server?

Thanks!

**Comment by vicente-gonzalez-ruiz** [comment]
OK, at this moment (in the current master's branch) the source is simulated (there is not a source). When a real source (Icecast, for example) feeds the splitter, the end-point of the source must be told to the splitter, because the source can be listening at any point.

The question I did yesterday is: ¿Which command are you using for running the simulator when the splitter obtains the stream from a source?

Thanks!!

**Comment by Pac23** [comment]
> OK, at this moment (in the current master's branch) the source is simulated (there is not a source). When a real source (Icecast, for example) feeds the splitter, the end-point of the source must be told to the splitter, because the source can be listening at any point.

:+1: 

> The question I did yesterday is: ¿Which command are you using for running the simulator when the splitter obtains the stream from a source?

The same command you tried,there were some issues in the code before i have fixed those,the only error that persists is due to connection being refused now https://imgur.com/a/8wgIHEQ reworked some code.

**Comment by vicente-gonzalez-ruiz** [comment]
@Pac23, I have seen the screenshot. Which message (of the screenshot) says that you are having refused connection problems?

**Comment by Pac23** [comment]
left hand side bottom you may see ,although there are some stream retrieving issues too so gotta fix those first too.

**Comment by vicente-gonzalez-ruiz** [comment]
OK @Pac23, yes, but this error comes from a peer, not from the splitter. This is because the splitter is not working and therefore, peers cannot connect. This message should be provided by the splitter and with the socket used for receiving the stream from the source.

**Comment by Pac23** [comment]
small update i ended up solving the source connection issues,peer connections still causing errors,working on it.

**Comment by vicente-gonzalez-ruiz** [comment]
Now the simulator "simulates" the generation of chunks. This is OK for now. Closing ...
