### ISSUE TITLE
Concise representation of a peer end-point for better visualisation.

### ISSUE THREAD

**Issue by sachinsngh165** [P2PSP/simulator#31]
Currently a peer is represented by it's (ip address, port), but it is too much to show on console. So we need a better way to represent an endpoint for better visualisation.

**Comment by sachinsngh165** [comment]
Is it possible that a peer can send chunk to another peer before sending 'hello' message to it ?

**Comment by vicente-gonzalez-ruiz** [comment]
Send, not. Receive, yes. Think about the [hello] is lost.

**Comment by cristobalmedinalopez** [comment]
What about a method where every peer is able to calculate the ID of the other peers based on their endpoints? Maybe something like a hash function.

**Comment by vicente-gonzalez-ruiz** [comment]
Yes, a hash function that is capable of translating the end-points of the peers to a positive integer of 7 bits, could work.

**Comment by sachinsngh165** [comment]
Can you please explain me what is the scope of this simulator. I Mean, are we want to run the simulator within a machine or between multiple machines (within the network or outside the network) ?  
I'm asking this question because to make hash function we need to know address scope of end-points.

**Comment by vicente-gonzalez-ruiz** [comment]
Although at this moment the simulator only runs teams in a host, but the idea is that it should be able to spawn teams in several hosts. So, the answer is: the endpoints can be any (always using IPv4, forget IPv6).

**Comment by sachinsngh165** [comment]
So for the moment should I only design the hash function for simulation within the host ? In this case, we just need to map port address to a number.

**Comment by cristobalmedinalopez** [comment]
Not really, we need to map (IP, port) to a number (or string?).

**Comment by sachinsngh165** [comment]
Don't you think if we map an end-point to 7 bit positive integer there would be collision in the hash function?

**Comment by sachinsngh165** [comment]
How about maintaining a shared memory to store dictionary ? Can we do that

**Comment by cristobalmedinalopez** [comment]
> How about maintaining a shared memory to store dictionary ? Can we do that

Is it really needed? If we use the same "hash function" for all entities it is not necessary to share any information.
Note that I used "hash function" because I think that it could be something different. In our case is not mandatory to avoid (or difficulty) its reconstruction.

**Comment by vicente-gonzalez-ruiz** [comment]
I would like that the "hash function" to generate only a 7-bits output for any input (only to have a printable character). Obviously, this has limitations (only 128 peer/team will work without collisions), but this does not matter.

If the splitter, when a peer is joining the team, assigns to the incoming peer a different integer id `Y` and, these ids are sent with the list of peers? Thus, any peer will know the id of the rest of the peers of the team and when the buffers are printed, we only need to print `Y mod 128`, where Y is mapped by a dictionary indexed by the end-points of the peers.

**Comment by sachinsngh165** [comment]
I was thinking the same but what if a new peer arrive, then how would old peer knows about its id ( as old peer are no longer connected via splitter_socket ) then i was thinking we can send that id with [Hello] message but what if [Hello] message get lost. 

On simple solution could be if splitter manage all the peer ids and whenever a peer encounter a new end-point it will get its id from splitter and that peer will add this entry to its own dictionary.

**Comment by sachinsngh165** [comment]
Beside, using Hash function would be best idea.

**Comment by sachinsngh165** [comment]
A hash function could be made by defining a relation b/w 8 bits blocks of ip address (e.g. x.x.x.x ) and finally with port number as follows:
`def hash(addr,port):
	blk = addr.split('.')
	bk = [int(x) for x in blk]
	sh = bk[0]^bk[1]^bk[2]
	sh = (sh + bk[3])%127
	sh = (sh + port%127)%127
	return sh`
what do you think ?

**Comment by cristobalmedinalopez** [comment]
I'm not sure about the operation of that function. For example, what if we have these two endpoints (192.168.2.1, 12345) and (192.168.1.2, 12345)? I guess that the same ID is assigned to both of them.
Anyway, it's a good start.

**Comment by sachinsngh165** [comment]
Yes you are right. But it is very difficult to avoid collisions because we are mapping 2^32 (4,294,967,295) addresses into 2^7 (127) address space.

I think the example you given is very least likely to happen in a local network. Because in a local network only host id change while network id remain same. 
e.g.
 
![local_ip](https://user-images.githubusercontent.com/16955349/40648734-c0408c06-634c-11e8-8f6a-e1016908dd57.png)

Even though i'm looking for a better solution. :)

**Comment by cristobalmedinalopez** [comment]
>it is very difficult to avoid collisions
Yes, I agree.
>Because in a local network only host id change while network id remain same
That is true, but the number of bit used by hosts will depend on the class of the network, in your example it is a Class C, so 8 bits are used by hosts. However if it is a Class B, you could use 16 bit for host instead of 8.

**Comment by vicente-gonzalez-ruiz** [comment]
Don't you like the idea of the id's assigned by the splitter? If the id's are natural numbers, allocated sequentially (0, 1, 2, ...), collisions will appear only when more than 128 peers are in the team. Moreover, these collisions could be also convenient in the case we want to determine the sender of a chunk.

**Comment by sachinsngh165** [comment]
> Don't you like the idea of the id's assigned by the splitter?
I think Splitter method would give very consistent results, and we can also give them sequential names. So representation would be nice. :-)

**Comment by vicente-gonzalez-ruiz** [comment]
Seems to be a good hash function.

**Comment by cristobalmedinalopez** [comment]
It looks good for me too :smile:

**Comment by vicente-gonzalez-ruiz** [comment]
No, it is impossible. However, it does not matter because we usually debug the buffer filling with small teams.

**Comment by sachinsngh165** [comment]
Please review my PR request .

**Comment by cristobalmedinalopez** [comment]
fixed in #32
