### ISSUE TITLE
Console/graphical isolation

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [P2PSP/simulator#8]
Currently, `simulator.py` imports `mathplotlib` even if the graphical output has not been activated. It would be useful if two different scripts were available (`simulate.py` and `play.py`, for example) in order to avoid using it in those systems where  `matplotlib` has not been sucessfully ported.

**Comment by abhay44** [comment]
@vicente-gonzalez-ruiz Could you elaborate more?

**Comment by cristobalmedinalopez** [comment]
It was resolved in 3758658
