### ISSUE TITLE
Using Internet Sockets instead of Unix sockets

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/simulator#9]
Turn AF_UNIX socket into AF_INET socket.

**Comment by abhay44** [comment]
@cristobalmedinalopez I would like to work on this? Could you explain in detail?

**Comment by cristobalmedinalopez** [comment]
Hi @abhay44,

Currently, we use Unix domain sockets to communicate between processes in the same host system. So, our simulator uses files as "address" instead of a (host, port) pair. If we turn AF_UNIX into AF_INET the translation between the simulator and the production code would be almost the same. We could apply all changes tested in the simulator to the production code in a faster way.

Thanks for your interest and happy holidays!

**Comment by cristobalmedinalopez** [comment]
@sachinsngh165 has this issue assigned now as a part of his participation in the GSoC 2018 program. Good luck!

**Comment by cristobalmedinalopez** [comment]
Fixed in PR #30
